spring.application.name=distributed-messaging

server.port=${SERVER_PORT:8081}

app.node.host=${NODE_HOST:localhost}
app.node.id=${NODE_ID:node-${server.port}}
app.node.url=http://${app.node.host}:${server.port}

app.zookeeper.connect-string=${ZK_CONNECT:localhost:2181,localhost:2182,localhost:2183}
app.zookeeper.session-timeout=${ZK_SESSION_TIMEOUT:5000}

app.wal.path=${WAL_PATH:./data/wal-${server.port}.log}
app.recovery.sync-on-startup=${SYNC_ON_STARTUP:true}

logging.level.com.messaging=INFO
logging.level.org.apache.zookeeper=INFO
